# Generated by Django 5.2.7 on 2025-12-01 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Rid', models.AutoField(primary_key=True, serialize=False)),
                ('RoomNumber', models.CharField(max_length=100)),
                ('RoomType', models.CharField(max_length=100)),
                ('RoomPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Capacity', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('Gid', models.AutoField(primary_key=True, serialize=False)),
                ('phoneno', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('BookingId', models.AutoField(primary_key=True, serialize=False)),
                ('CheckInDate', models.DateField()),
                ('CheckOutDate', models.DateField()),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=100)),
                ('Gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.guestprofile')),
                ('Rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.room')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentId', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentDate', models.DateField()),
                ('PaymentMethod', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.booking')),
            ],
        ),
    ]
